version: '3'
services:
  ekolod-probe:
    build:
      context: .
      dockerfile: docker/Dockerfile.probe
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/app/configs:ro

  ekolod-ui:
    build:
      context: ./ui
      dockerfile: docker/Dockerfile.ui
    ports:
      - "5173:5173"  # SvelteKit dev server typically runs on 5173
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - EKOLOD_API_URL=http://ekolod-probe:8080
    depends_on:
      - ekolod-probe
    command: npm run dev -- --host

  configmap-reload:
    build:
      context: .
      dockerfile: docker/Dockerfile.configmap-reload
    volumes:
      - ./configs:/configs:ro
