targets:
  - name: "Example"
    url: "https://example.com"
    interval: "10s"
    timeout: "5s"
  - name: "Google"
    url: "https://www.google.com"
    interval: "15s"
    timeout: "5s"
  - name: "Cloudflare"
    url: "https://cloudflare.com"
    interval: "15s"
    timeout: "5s"

server:
  port: 8080
