FROM golang:1.21-alpine

# Install wait-for-it
RUN apk add --no-cache bash
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /ekolod-collector ./cmd/collector

EXPOSE 8080

# Use wait-for-it to wait for the database before starting the API
CMD ["sh", "-c", "wait-for-it timescaledb:5432 -- /ekolod-collector"]