name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - "cmd/probe/**"
      - "pkg/config/**"
      - "pkg/probe/**"
      - "pkg/server/**"
      - "probe/**"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "cmd/probe/**"
      - "pkg/config/**"
      - "pkg/probe/**"
      - "pkg/server/**"
      - "probe/**"
      - "go.mod"
      - "go.sum"

env:
  REGISTRY: ghcr.io
  PROBE_IMAGE_NAME: ${{ github.repository }}/probe

jobs:
  build-and-push-probe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROBE_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./probe/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
