name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  PROBE_IMAGE_NAME: ${{ github.repository }}/probe

jobs:
  build-and-push-probe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Only run this job if relevant files for the probe have changed
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && 
       (contains(github.event.pull_request.files.*.filename, 'cmd/probe/') ||
        contains(github.event.pull_request.files.*.filename, 'pkg/') ||
        contains(github.event.pull_request.files.*.filename, 'probe/') ||
        contains(github.event.pull_request.files.*.filename, 'go.mod') ||
        contains(github.event.pull_request.files.*.filename, 'go.sum')))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROBE_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./probe/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Add similar jobs for API and UI components in the future
